FROM ubuntu:xenial-20180123

LABEL \
org.opencontainers.image.created="2018-01-31T20:00:00Z+01:00" \
org.opencontainers.image.authors="nicholas@dille.name" \
org.opencontainers.image.source="https://github.com/nicholasdille/docker" \
org.opencontainers.image.revision="566a5e0" \
org.opencontainers.image.vendor="Nicholas Dille"

#...
