#escape=`
FROM microsoft/iis:windowsservercore-1709

RUN C:\Windows\System32\inetsrv\appcmd.exe set config "Default Web Site" /section:system.webServer/staticContent /+"[fileExtension='.md',mimeType='application/octet-stream']"
SHELL [ "powershell", "-command" ]

WORKDIR /inetpub/wwwroot
ADD lib lib
ADD images images
ADD media media
ADD slides slides
ADD sponsors sponsors
ADD slides_offline.html index.html

RUN Remove-Item -Path c:\inetpub\wwwroot\iisstart.* -Force
